server:
  port: 8001
spring:
   profiles:
     active: dev
---
spring:
  profiles: dev
  #redis相关配置
  redis:
    host: 192.168.50.180
    database: 0
    port: 6379
    password: qft123456
    timeout: 60000
    pool:
      max-wait: -1
      max-idle: 500
      min-idle: 0
  http:
    multipart:
      max-file-size: 100Mb
      max-request-size: 100Mb
    #thymeleaf配置
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    cache: false

---
spring:
  profiles: test
  #redis相关配置
  redis:
    host: 192.168.1.248
    database: 0
    port: 6379
    password: 13579qaz
    timeout: 60000
    pool:
      max-wait: -1
      max-idle: 500
      min-idle: 0

  http:
    multipart:
      max-file-size: 100Mb
      max-request-size: 100Mb
  #thymeleaf配置
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    cache: false

---

spring:
  profiles: prod-test
  #redis相关配置
  redis:
    host: 127.0.0.1
    database: 0
    port: 6379
    password: 
    timeout: 60000
    pool:
      max-wait: -1
      max-idle: 500
      min-idle: 0

  http:
    multipart:
      max-file-size: 100Mb
      max-request-size: 100Mb
  #thymeleaf配置
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    cache: false

---

spring:
  profiles: prod
  #redis相关配置
  redis:
    host: 172.18.203.179
    database: 0
    port: 6379
    password: 1EC4b2Iq
    timeout: 60000
    pool:
      max-wait: -1
      max-idle: 500
      min-idle: 0

  http:
    multipart:
      max-file-size: 100Mb
      max-request-size: 100Mb
    #thymeleaf配置
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    cache: false
